### PR TITLE
update gorouter for prometheus scraping

### PR DESCRIPTION
**Pull request by Benjamintf1**
https://github.com/cloudfoundry/gorouter/pull/307

**Not sure the exact process for adding the go mod changes or the spec changes or the gorouter changes though.**
* [x] I have viewed signed and have submitted the Contributor License Agreement

* [x] I have made this pull request to the `develop` branch

* [x] I have run all the unit tests using `scripts/run-unit-tests-in-docker`

* [ ] (Optional) I have run Routing Acceptance Tests and Routing Smoke Tests on bosh lite

* [ ] (Optional) I have run CF Acceptance Tests on bosh lite

### CODE REVIEW

**Comment by Benjamintf1** [comment]
We're going to look into fixing the empty prom_scraper config problem in metrics-agent and prom_scraper in their repsective releases rather then the hack. We'd still be interested in both generalized feedback as well as feedback on how to handle the go.mod changes, the spec changes, and the submoduling of gorouter.

**Comment by Benjamintf1** [comment]
we've cut releases for loggregator-agent-release and metrics-discovery to properly handle empty prom_scraper.yml files.

**Comment by Benjamintf1** [comment]
rebased cause weird mergy things.

**Comment by Benjamintf1** [comment]
hmm, I'm confused.

**Review by geofffranks — APPROVED** [review]

**Pull request merged**
