### PR TITLE
Update uaa-go-client;

### PR DESCRIPTION
**Pull request by joergdw**
* A short explanation of the proposed change: Update of go-uaa-client

* An explanation of the use cases your change solves: Fix security-issues due to an outdated jwt-go-version.

* Instructions to functionally test the behavior change using operator interfaces (BOSH manifest, logs, curl, and metrics)

* Expected result after the change: Behaviour as before

* Current result before the change

* Links to any other associated PRs

* [X] I have viewed signed and have submitted the Contributor License Agreement

* [X] I have made this pull request to the `develop` branch

* [X] I have run all the unit tests using `scripts/run-unit-tests-in-docker`

* [-] (Optional) I have run Routing Acceptance Tests and Routing Smoke Tests on bosh lite

* [-] (Optional) I have run CF Acceptance Tests on bosh lite

### CODE REVIEW

**Comment by ameowlia** [comment]
@ebroberson can you review this?

**Comment by ebroberson** [comment]
Sure thing!

**Review by ebroberson — APPROVED** [review]
LGTM

**Comment by ameowlia** [comment]
Merging based on @ebroberson 's review.

**Pull request merged**
