### PR TITLE
Ensure gorouter-healthchecker doesn't restart gorouter forever on fai…

### PR DESCRIPTION
**Pull request by geofffranks**
…lure

Signed-off-by: Amelia Downs <adowns@vmware.com>

* A short explanation of the proposed change:

* An explanation of the use cases your change solves

* Instructions to functionally test the behavior change using operator interfaces (BOSH manifest, logs, curl, and metrics)

* Expected result after the change

* Current result before the change

* Links to any other associated PRs

* [ ] I have viewed signed and have submitted the Contributor License Agreement

* [ ] I have made this pull request to the `develop` branch

* [ ] I have run all the unit tests using `scripts/run-unit-tests-in-docker`

* [ ] (Optional) I have run Routing Acceptance Tests and Routing Smoke Tests on bosh lite

* [ ] (Optional) I have run CF Acceptance Tests on bosh lite

### CODE REVIEW

**Comment by geofffranks** [comment]
We should redo this logic after https://github.com/cloudfoundry/cf-networking-helpers/tree/healthchecker-limit-restarts is PR'd and marged. Using monit to solve this won't work well.

**Comment by geofffranks** [comment]
FailureCounterFile logic implemented + latest healthchecker has been pulled into this PR. Should be ready for review/merging.

**Review by ameowlia — APPROVED** [review]
LGTM

**Comment by ameowlia** [comment]
> We should redo this logic after https://github.com/cloudfoundry/cf-networking-helpers/tree/healthchecker-limit-restarts is PR'd and marged. Using monit to solve this won't work well.

This link is broken for me.

**Pull request merged**
