### PR TITLE
Consume per request metrics reporting config

### PR DESCRIPTION
**Pull request by stefanlay**
* A short explanation of the proposed change:
This change addresses https://github.com/cloudfoundry/gorouter/issues/159 and makes new properties from the gorouter consumable.

See instructions and explanation in related PR for gorouter: https://github.com/cloudfoundry/gorouter/pull/275

* [x] I have viewed signed and have submitted the Contributor License Agreement

* [x] I have made this pull request to the `develop ` branch

* [x] I have run all the unit tests using `scripts/run-unit-tests-in-docker`

### CODE REVIEW

**Comment by ameowlia** [comment]
@stefanlay can you add which metrics specifically will be turned on/off in the description? Other than that, lgtm.

**Comment by plowin** [comment]
Hi, when will this be released? :)

**Comment by ameowlia** [comment]
😭 When I get our red pipelines green. Failures are unrelated to this change. 

Please keep pinging about it. Squeaky wheel gets the grease and all that.

**Comment by plowin** [comment]
Pinging again as requested 😀 
Maybe we are lucky and the tires are rolling again 🚀 

Thanks for your efforts here!

**Comment by ameowlia** [comment]
The pipeline is green as of yesterday and all the new commits (including yours) should be going through today. Expect good news soon!

Thank you for your patience!

**Comment by howardyoo** [comment]
Hi all, I'm also interested to see this fix being available - any timelines of this released to the customers?

**Comment by ameowlia** [comment]
This was released on March 19 in [0.213.0](https://github.com/cloudfoundry/routing-release/releases/tag/0.213.0)!! 🎉 🐱 🍰 🎈

**Pull request merged**
